### ISSUE TITLE
difference between this repo and openMF message gateway

### ISSUE THREAD

**Issue by francisguchie** [mgeiss/mifos-twilio-bridge#5]
@mgeiss , @avikganguly01 
I would like to know which of the repos is the best to use. The documentation is a little confusing

**Comment by awasum** [comment]
@francisguchie Please use this: https://github.com/openMF/message-gateway
See manuals for configuration: https://mifosforge.jira.com/wiki/spaces/docs/pages/166658049/Message+Gateway+Configuration
https://mifosforge.jira.com/wiki/spaces/docs/pages/165871671/SMS+Campaigns

For any problems. Join the mailing list and ask questions there.

**Comment by francisguchie** [comment]
thanks @awasum 
this is a quick response

**Comment by francisguchie** [comment]
@awasum 
which mailing list do i join and how to join it ?

**Comment by awasum** [comment]
http://fineract.apache.org/#contribute

https://mifos.org/resources/community/communications/

Please close this issue.

**Comment by francisguchie** [comment]
thank you so much @awasum
